### ISSUE TITLE
[BUG] Loading loop cause Uncaught SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by kamitanw** [kmvan/x-prober#101]
- OS: Centos 8
- PHP version: 7.4.9
- Browser: Chrome latest stable

## Expected behavior
Loading successful without problem

## Actual behavior
The page showing loading always,even refresh.

## Other description
there are few errors in console :

```
Uncaught SyntaxError: Unexpected token ':'
prober.php?action=script&v=6.1:1 Uncaught TypeError: Cannot read property 'redis' of undefined
    at Module.<anonymous> (prober.php?action=script&v=6.1:1)
    at n (prober.php?action=script&v=6.1:1)
    at prober.php?action=script&v=6.1:1
    at prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
n @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
prober.php?action=script&v=6.1:1 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at J.<anonymous> (prober.php?action=script&v=6.1:1)
    at Generator.next (<anonymous>)
    at ne (prober.php?action=script&v=6.1:1)
    at a (prober.php?action=script&v=6.1:1)
    at prober.php?action=script&v=6.1:1
    at new Promise (<anonymous>)
    at J.fetch (prober.php?action=script&v=6.1:1)
    at new J (prober.php?action=script&v=6.1:1)
    at Module.<anonymous> (prober.php?action=script&v=6.1:1)
    at n (prober.php?action=script&v=6.1:1)
(anonymous) @ prober.php?action=script&v=6.1:1
ne @ prober.php?action=script&v=6.1:1
a @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
J @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
n @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
prober.php?action=script&v=6.1:1 Uncaught (in promise) TypeError: Cannot read property 'authorization' of undefined
    at n (prober.php?action=script&v=6.1:1)
    at next (<anonymous>)
    at ge (prober.php?action=script&v=6.1:1)
    at a (prober.php?action=script&v=6.1:1)
    at prober.php?action=script&v=6.1:1
    at new Promise (<anonymous>)
    at r (prober.php?action=script&v=6.1:1)
    at prober.php?action=script&v=6.1:1
    at new Promise (<anonymous>)
    at be (prober.php?action=script&v=6.1:1)
n @ prober.php?action=script&v=6.1:1
ge @ prober.php?action=script&v=6.1:1
a @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
r @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
be @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
Bt @ prober.php?action=script&v=6.1:1
a @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
Lt @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
n @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
(anonymous) @ prober.php?action=script&v=6.1:1
```

and here is the detail of the error:
`
......","scriptPath":"\/data\/web\/public\/prober.php","diskUsage":{"value":24092635136,"max":988718399487.:}},"phpExtensions":{"redis":true,"sqlite3":true,"memcache":false,"memcached":true,"opcache":true,"opcacheEnabled":true,......
`

How could I fix it,
Thank you!

**Comment by kmvan** [comment]
Thank you report.
Have online URL?

**Comment by kamitanw** [comment]
> I found the bug.

thank you for helping!

**Comment by kmvan** [comment]
@kamitanw Could you download the DEV version and try it?
https://github.com/kmvan/x-prober/tree/dev/dist

**Comment by kamitanw** [comment]
@kmvan Thank you for your helping!
seems it will not stuck at loading loop,
but the problem still not resolve,
the page wont load complete,
only background color,

and an error alert "Fetch error, please refresh page."

still here
`
.....","diskUsage":{"value":23705788416,"max":988718399487.:}},"phpExt......
                                                                                         ^^^
`

if I changed diskUsage value and max to 0,
`
'diskUsage' => array( 'value' => 0, 'max' => 0
`
it will got fixed (although disk usage will be 0)

maybe something wrong with HelperApi::getDiskTotalSpace() ?

Thank you.

**Comment by kmvan** [comment]
Any online URL?

**Comment by kamitanw** [comment]
here:
https://www.sostm.org/prober.php

thank you!

**Comment by kmvan** [comment]
Could you create a PHP file `test.php` and paste code:
```php
<?php
var_dump(disk_total_space(__DIR__));
```

And access via URL. What information is displayed?

**Comment by kamitanw** [comment]
sure,
here is the result :
`
float(988718399488)
`

**Comment by kmvan** [comment]
Very strange.
![image](https://user-images.githubusercontent.com/3839554/91632855-5f767400-ea16-11ea-9f3c-d42070ebc388.png)

I don't what is it `.:`.
May I got your server ssh or ftp sign information? I think I need to debug on the server.
Could you send an email about sign-in information of server to kmvan.com@gmail.com?

**Comment by kamitanw** [comment]
that's really helpful,
Big thanks!!

I'll setup a same environment on vps for you(cause the problem server is dedicated server and use ipmi to login),
and i'll give you login info then,
thank you again!

**Comment by kmvan** [comment]
Is it using CloudFlare?
Try to access via `http://IP/prober.php`?

**Comment by kamitanw** [comment]
still same error,
and i'm sorry i forgot to provide some information:
`
server software: litespeed
`
php.ini custom setting
`
[igbinary]
session.serialize_handler=igbinary
igbinary.compact_strings=On
apc.serializer=igbinary

[custom]
magic_quotes_gpc = Off
register_globals = Off
default_charset = UTF-8;
safe_mode = Off
mysql.connect_timeout = 300
session.gc_maxlifetime = 3600
allow_url_fopen = on

session.save_path = "/tmp/php"

zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=100000
opcache.max_wasted_percentage=10
opcache.use_cwd=1
opcache.max_file_size=0

opcache.file_cache=/tmp/opcache
opcache.file_cache_consistency_checks=1
opcache.huge_code_pages=1
opcache.lockfile_path=/tmp
opcache.fast_shutdown=1

`

i'm not sure is it helpful...?

**Comment by kmvan** [comment]
Access via IP, still not work?

**Comment by kmvan** [comment]
If there is no more information, I will close the issue. But this does not mean that this issue cannot be discussed, please feel free to discuss and open it.
