### ISSUE TITLE
请问能否把服务器ip隐藏掉

### ISSUE THREAD

**Issue by eicky** [kmvan/x-prober#102]
- OS:Debian
- PHP version: 7.2

请问能把服务器ip去除吗？这样暴露了服务器ip

**Comment by kmvan** [comment]
IP 地址是公开的，不会造成任何安全问题。因为直接 ping 域名就能得出 IP 了。如果使用了 CDN，那么 IP 也是 CDN 的 IP，所以这个功能没有任何影响的。

**Comment by eicky** [comment]
但是我套了CDN，我看服务器ip还是显示的我本机实际ip地址，因为内网和公网是同ip的问题导致的吗？

**Comment by kmvan** [comment]
用手机流量查看，应该是cdn ip。

**Comment by eicky** [comment]
> 用手机流量查看，应该是cdn ip。

手机也查看了，确实是服务器的真实ip

**Comment by kmvan** [comment]
这不科学，方便邮件我探针地址吗？我测试下

**Comment by eicky** [comment]
> 这不科学，方便邮件我探针地址吗？我测试下

你来个TG或者邮件地址都行，我直接找你

**Comment by kmvan** [comment]
kmvan.com@gmail.com

**Comment by moerfutin** [comment]
最新的探针，还是显示服务器真是IP呢，逃了cloudflare的cdn

**Comment by kmvan** [comment]
配置文件选择禁用功能 `serverIp`

**Comment by moerfutin** [comment]
> 配置文件选择禁用功能 `serverIp`

感谢，但是下载的单文件php，没找到在哪修改呢。 T.T请原谅我是技术小白

**Comment by kmvan** [comment]
https://github.com/kmvan/x-prober/blob/master/xconfig.json
仿照这个配置文件编辑你想要的内容，保存在探针同目录下

**Comment by moerfutin** [comment]
> https://github.com/kmvan/x-prober/blob/master/xconfig.json
> 仿照这个配置文件编辑你想要的内容，保存在探针同目录下

感谢，终于搞定了。但是xconfig.json这个示例里面的这一段可以删掉么，或者需要怎么改？ 

>   // You can set nodes for X-Prober
>  "nodes": [
>   ["node-1", "http://localhost/prober/.tmp/"],
>   ["node-3", "http://localhost/prober/.tmp/"]  ]

因为有了它，就报如下图的错。
![image](https://user-images.githubusercontent.com/9960618/112793717-5d51c200-9098-11eb-84e8-8772a7d60c36.png)

**Comment by kmvan** [comment]
动手试试，注意未位逗号

On Mar 29, 2021 14:10, moerfutin ***@***.***> wrote:

https://github.com/kmvan/x-prober/blob/master/xconfig.json
仿照这个配置文件编辑你想要的内容，保存在探针同目录下

感谢，终于搞定了。但是xconfig.json这个示例里面的这一段可以删掉么，或者需要怎么改？

// You can set nodes for X-Prober
"nodes": [
["node-1", "http://localhost/prober/.tmp/"],
["node-3", "http://localhost/prober/.tmp/"] ]

因为有了它，就报如下图的错。
[image]<https://user-images.githubusercontent.com/9960618/112793717-5d51c200-9098-11eb-84e8-8772a7d60c36.png>

**Comment by moerfutin** [comment]
撒花~ 再次感谢神速~
