### ISSUE TITLE
[BUG] Incorrect CPU/RAM/SWAP usage

### ISSUE THREAD

**Issue by thistehneisen** [kmvan/x-prober#11]
- OS: Linux ilze 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- PHP version: 7.0.33

** Report content **
https://www.nils.digital/x.php

**Comment by kmvan** [comment]
Thanks your report.
Is it cPanel virtual host?

**Comment by thistehneisen** [comment]
It's Plesk

**Comment by kmvan** [comment]
Thanks, I got the reason.

Plesk's `open_basedir` setting is: `/var/www/vhosts/nils.digital/:/tmp/`.
The CPU/memory/network stats information requires that the dir `/proc/` should be read.
Like `/var/www/vhosts/nils.digital:/tmp/:/proc/`. 
So you can add `:/proc/` to `open_basedir` in php.ini and works fine.

**Comment by thistehneisen** [comment]
True, that did work (you can see it live). The disk usage is unavailable, I guess that's permissions also?

**Comment by kmvan** [comment]
The disk usage information calls by `disk_total_space('/')` function, you can comment the `open_basedir` config if you want to show disk usage info. But not recommend, it is dangerous permission.

**Comment by kmvan** [comment]
Can be talking continue after closed the issue.
