### ISSUE TITLE
Any solution to make these available?

### ISSUE THREAD

**Issue by if1y** [kmvan/x-prober#128]
- OS: CentOS 7.6.1810
- PHP version: 7.0

Much info unavailable, as you can see from the screenshot.
`Server uptime` and `CPU model` are unavailable too.

![image](https://user-images.githubusercontent.com/32222791/107468319-b4600e00-6ba2-11eb-85e6-46a80d43dd32.png)

**Comment by if1y** [comment]
噢对了，因为我看 issue 区英文内容挺多，所以用了英文

**Comment by kmvan** [comment]
这种情况可能是没有 /proc 目录读取权限导致的。

**Comment by if1y** [comment]
确实，检查发现所有者是 `65534`（nobody），尝试 `sudo chown` 也无权限，意味着是母鸡限制无解了？

**Comment by kmvan** [comment]
什么面板？什么系统？

**Comment by if1y** [comment]
CentOS 7 LXC虚拟化 + 宝塔面板

**Comment by kmvan** [comment]
宝塔的话，去掉防跨站选项

**Comment by if1y** [comment]
还真是。可以了，感谢。

----------------
旧版宝塔默认不开，新版宝塔开，我都没想到防跨站。

**Comment by kmvan** [comment]
其实可以把 `/proc` 目录作为允许访问，毕竟这个目录只读，而且并没什么机密信息。例如在 `nginx` 的 `fastcgi.conf` 文件添加：
```
fastcgi_param  PHP_VALUE          "open_basedir=$document_root:/tmp/:/proc/";
```
这样每个主机名都能访问 `/proc` 目录，但宝塔具体 `nginx` 配置文件放在哪，文件名是什么，这个需要可以自己研究。
