### ISSUE TITLE
[Feature request]建议内存更详细点

### ISSUE THREAD

**Issue by ClarkeCheng** [kmvan/x-prober#13]
建议内存像这样有 Total Memory，Cache Memory 和 Real Memory
![snipaste_20190125082332](https://user-images.githubusercontent.com/17330505/51717202-f466fd80-207a-11e9-9808-3fc275e58369.png)

**Comment by kmvan** [comment]
不错的建议，我打算在一个进度条中同时显示多种内存

**Comment by kmvan** [comment]
2.1.0 已加入
