### ISSUE TITLE
Parse error: syntax error, unexpected '?' in D:\phpStudy\PHPTutorial\WWW\test\x.php on line 2

### ISSUE THREAD

**Issue by kmvan** [kmvan/x-prober#137]
Parse error: syntax error, unexpected '?' in D:\phpStudy\PHPTutorial\WWW\test\x.php on line 2
目前7.2和7.3的版本都碰到这个情况，6.5的版本正常
另外节点应该如何设置呢？

_Originally posted by @qingyuan0o0 in https://github.com/kmvan/x-prober/issues/127#issuecomment-784923590_

**Comment by kmvan** [comment]
PHP 版本？

**Comment by qingyuan0o0** [comment]
php 5.6.27

**Comment by kmvan** [comment]
知道问题了，误用了php7的语法了

**Comment by kmvan** [comment]
试试下载  https://github.com/kmvan/x-prober/tree/dev/dist  开发版，应该正常了

**Comment by kmvan** [comment]
> 这个开发板现在页面正常显示了
> 在azure的php没办法正常获取数据
> php 5.6.40
> 另外经过6.5的版本和7.3开发板测试服务器跑分在IO那一个项
> 数值为负数，计算结果也不对

有在线地址吗？
另外跑分负数，说明该项水平较低，无下限的。

**Comment by qingyuan0o0** [comment]
0o0.azurewebsites.net/x73.php

**Comment by kmvan** [comment]
500 错误了，开启 PHP 错误显示看看？

**Comment by qingyuan0o0** [comment]
不排除是权限不足，这个站点我只能FTP上传页面，没有系统权限

**Comment by kmvan** [comment]
那试试下面这个文件，程序内部启用了错误显示。
[prober.zip](https://github.com/kmvan/x-prober/files/6035309/prober.zip)

**Comment by qingyuan0o0** [comment]
刚刚发的这个微软的后台可以后台执行cmd命令，但是某些命令没有权限，分为C盘和D盘，我分别查看过，可能是虚拟机

**Comment by kmvan** [comment]
即使没权限也不应该直接500的

**Comment by qingyuan0o0** [comment]
已经上传了，文件名没变

**Comment by kmvan** [comment]
还是500空白内容。你能运行cmd的话，可以用cmd修改一下php设置或查看一下错误日志记录，如果有这个权限。

**Comment by qingyuan0o0** [comment]
比较难，要用工具执行一句话mm，然后上传cmd.exe才可以。。页面中有web.config

**Comment by kmvan** [comment]
这个就没什么办法了，windows上的限制比较多，特别是 IIS，一般来说PHP不会在windows的IIS运行。

**Comment by qingyuan0o0** [comment]
明白了，在linux下测试正常，版本是php 7.2.20
请问多节点在同一个页面显示，应该如何配置，是否有说明呢？

**Comment by kmvan** [comment]
多节点参考配置文件 https://github.com/kmvan/x-prober/blob/master/xconfig.json 中的 nodes 项。确保每个节点地址都存在探针。

**Comment by kmvan** [comment]
我认为该问题已经解决，先行关闭。如果需要继续探讨可以继续在下面讨论。
