### ISSUE TITLE
后面的选项卡（tabs）似乎不会高亮

### ISSUE THREAD

**Issue by xanadus0** [kmvan/x-prober#145]
- OS: Debian 10
- PHP version: 7.3

后面的选项卡（tabs）似乎不会高亮，不会高亮的选项卡数量可能与屏幕尺寸有关。

> https://******/x.php#myInfo

![图片](https://user-images.githubusercontent.com/35560692/110730113-dc529800-825a-11eb-9c40-33f817741e2e.png)

**Comment by kmvan** [comment]
正常，没有达到相应位置


-------- Original message --------

**Comment by xanadus0** [comment]
也许设计上是这样，但是感官上有点反直觉（点击那个选项卡，却没有高亮，而是高亮前面的）。

当然以上仅是我的个人观点。

**Comment by kmvan** [comment]
目前是两种高亮，一种是悬停高亮，一种是当前高亮。如果点击后直接变成当前高亮，那么点最后一个的时候，有可能会出现两个一样的当前高亮，看起来更加奇怪。所以针对这种情况，我不想让体验造成一种“欺骗”的感觉。
当然如果要最后一个也出现当前高亮，那么只能是把底部的空间腾出一个屏幕大，这样最低的一项就能靠近屏幕顶端从而显示出当前高亮，然而因为存在黑边框的设计，空白一片会略显突兀。综合起来我选择目前的方案。如果你有更好的方法，不妨说说。
