### ISSUE TITLE
openwrt怎么运行啊？

### ISSUE THREAD

**Issue by VwEl** [kmvan/x-prober#150]
- OS:
- PHP version: php7 | 7.4.7-1

Fatal error: Uncaught Error: Call to undefined function filter_input() in /www/tz/x.php:635 Stack trace: #0 /www/tz/x.php(635): InnStudio\Prober\Components\Bootstrap\Action->__construct() #1 /www/tz/x.php(654): InnStudio\Prober\Components\Bootstrap\Bootstrap->__construct() #2 {main} thrown in /www/tz/x.php on line 635

**Comment by kmvan** [comment]
filter 默认启用的。可能在安装 php 时候加上了  `--disable-filter` 参数就被禁用了

**Comment by VwEl** [comment]
> 
> 
> filter 默认启用的。可能在安装 php 时候加上了 `--disable-filter` 参数就被禁用了

感谢！ 需要额外安装php*-mod-filter *是当前版本
