### ISSUE TITLE
请问怎么添加多个nodes?

### ISSUE THREAD

**Issue by LAOZTK** [kmvan/x-prober#154]
看演示站里面除了服务器本身的详情信息外，还有node-1,node-2,node-3的信息。

**Comment by kmvan** [comment]
https://github.com/kmvan/x-prober/blob/master/xconfig.json

参考配置文件

**Comment by LAOZTK** [comment]
最新版好像 服务器 IPv4 服务器 IPv6 服务器软件 这三个选项 会有重复哦？？ 看演示站中的也是重复的

**Comment by kmvan** [comment]
bug，下个版本修复

**Comment by LAOZTK** [comment]
好的，感谢回复

**Comment by LAOZTK** [comment]
不好意思再次打扰，修改后xconfig.json后编译得到的文件和release下载的文件是一样的 功能没有增减
PHP 版本为 8.0.7
系统为 Linux : Ubuntu 21.04 x86_64
执行步骤是:
git clone https://github.com/kmvan/x-prober.git
cd x-prober
修改 xconfig.json
{
  "disabled": ["serverIp", "phpInfoDetail"],
  "nodes": [
    ["node-1", "https://xxxx.com"]
  ]
}
npm install
composer install; composer dumpautoload -o
npm run build
npm run build:php
最后下载 dist/prober.php 
请问是哪个步骤错了？
从文件修改时间上来看，编译后prober.php是有被修改的
希望大佬不吝赐教

**Comment by kmvan** [comment]
只需要放配置文件就可以

**Comment by LAOZTK** [comment]
只需要在 x.php 同级目录下添加一个  xconfig.json 即可？ 不需要重新编译？

**Comment by kmvan** [comment]
不需要

**Comment by LAOZTK** [comment]
可以了，我还纳闷了半天，编译了好多次，谢谢指点
