### ISSUE TITLE
使用apache2 一直显示⏳ Loading...

### ISSUE THREAD

**Issue by LAOZTK** [kmvan/x-prober#156]
- OS: Ubuntu 21.04 x86_64
- PHP version: 8.0.7
- apache2 version: 2.4.46
- x-prober version: 7.7
访问一直显示 loading ，查看日志显示文件找不到
 [php:error] [pid 2745708]  script '/var/www/blog/x.php' not found or unable to stat
请问是apache2规则配置问题，还是有bug？但是用其他php探针是正常的

**Comment by kmvan** [comment]
有 php_errors.log 日志记录信息吗？

**Comment by LAOZTK** [comment]
log_errors on;
error_log /var/log/php_errors.log;
我已经配置了这两项，但是并没有任何错误信息，甚至连错误日志文件都没有生成
从 apache2 日志中也没有得到错误

**Comment by LAOZTK** [comment]
附上 apache2 debug 日志

[Wed Jun 30 21:44:07.004981 2021] [deflate:debug] [pid 2947823] mod_deflate.c(867): [client 159.138.xx.xx:55376] AH01384: Zlib: Compressed 4044 to 2060 : URL /x.php
[Wed Jun 30 21:44:07.344356 2021] [ssl:debug] [pid 2947823] ssl_engine_kernel.c(415): [client 159.138.xx.xx:55376] AH02034: Subsequent (No.4) HTTPS request received for child 3 (server 123456.com:443), referer: https://123456.com/x.php
[Wed Jun 30 21:44:07.344488 2021] [authz_core:debug] [pid 2947823] mod_authz_core.c(815): [client 159.138.xx.xx:55376] AH01626: authorization result of Require all granted: granted, referer: https://123456.com/x.php
[Wed Jun 30 21:44:07.344511 2021] [authz_core:debug] [pid 2947823] mod_authz_core.c(815): [client 159.138.xx.xx:55376] AH01626: authorization result of <RequireAny>: granted, referer: https://123456.com/x.php
[Wed Jun 30 21:44:07.345145 2021] [deflate:debug] [pid 2947823] mod_deflate.c(867): [client 159.138.xx.xx:55376] AH01384: Zlib: Compressed 4044 to 2060 : URL /x.php, referer: https://123456.com/x.php
[Wed Jun 30 21:44:09.528466 2021] [ssl:debug] [pid 2947823] ssl_engine_kernel.c(415): [client 159.138.xx.xx:55376] AH02034: Subsequent (No.5) HTTPS request received for child 3 (server 123456.com:443)
[Wed Jun 30 21:44:09.528635 2021] [authz_core:debug] [pid 2947823] mod_authz_core.c(815): [client 159.138.xx.xx:55376] AH01626: authorization result of Require all granted: granted
[Wed Jun 30 21:44:09.528669 2021] [authz_core:debug] [pid 2947823] mod_authz_core.c(815): [client 159.138.xx.xx:55376] AH01626: authorization result of <RequireAny>: granted
[Wed Jun 30 21:44:09.529548 2021] [deflate:debug] [pid 2947823] mod_deflate.c(867): [client 159.138.xx.xx:55376] AH01384: Zlib: Compressed 4044 to 2060 : URL /x.php
[Wed Jun 30 21:44:09.869658 2021] [ssl:debug] [pid 2947823] ssl_engine_kernel.c(415): [client 159.138.xx.xx:55376] AH02034: Subsequent (No.6) HTTPS request received for child 3 (server 123456.com:443), referer: https://123456.com/x.php
[Wed Jun 30 21:44:09.869773 2021] [authz_core:debug] [pid 2947823] mod_authz_core.c(815): [client 159.138.xx.xx:55376] AH01626: authorization result of Require all granted: granted, referer: https://123456.com/x.php
[Wed Jun 30 21:44:09.869796 2021] [authz_core:debug] [pid 2947823] mod_authz_core.c(815): [client 159.138.xx.xx:55376] AH01626: authorization result of <RequireAny>: granted, referer: https://123456.com/x.php
[Wed Jun 30 21:44:09.870427 2021] [deflate:debug] [pid 2947823] mod_deflate.c(867): [client 159.138.xx.xx:55376] AH01384: Zlib: Compressed 4044 to 2060 : URL /x.php, referer: https://123456.com/x.php
[Wed Jun 30 21:44:14.879630 2021] [ssl:debug] [pid 2947823] ssl_engine_io.c(1102): [client 159.138.xx.xx:55376] AH02001: Connection closed to child 3 with standard shutdown (server 123456.com:443)

**Comment by LAOZTK** [comment]
touch /var/log/php_errors.log
systemctl restart apache2
还是没有记录
![image](https://user-images.githubusercontent.com/38147713/123979189-12c34700-d9f3-11eb-811d-3299b04253ab.png)
![image](https://user-images.githubusercontent.com/38147713/123979307-2e2e5200-d9f3-11eb-98f3-44dd09218ebf.png)

**Comment by kmvan** [comment]
有在线demo吗？

**Comment by LAOZTK** [comment]
有啊 一直是公网服务器上在测试

**Comment by kmvan** [comment]
地址贴来看看

**Comment by LAOZTK** [comment]
blog.9420.me/x.php

**Comment by LAOZTK** [comment]
php信息:
https://blog.9420.me/phpinfo.php

**Comment by kmvan** [comment]
新建一个php文件作为测试，内容是：

```php
<?php
var_dump((string) \filter_input(\INPUT_GET, 'action', \FILTER_SANITIZE_STRING));
```

保存后通过浏览器访问文件加上 `?action=test` ，这时候页面会输出什么？

**Comment by LAOZTK** [comment]
string(0) ""

**Comment by LAOZTK** [comment]
string(4) "test"

**Comment by kmvan** [comment]
这就很奇怪了。有没有试过nginx？

**Comment by LAOZTK** [comment]
我换了个文件就正常了 白天编译了很多次 文件有点乱 可能这个文件在编译的时候有环节弄错了 
啊啊啊 实在不好意思 让作者大大费心了
