### ISSUE TITLE
xconfig配置多节点，名称相同时会导致加载不出来

### ISSUE THREAD

**Issue by LAOZTK** [kmvan/x-prober#157]
- OS:Ubuntu 20.04.2
- PHP version: 8.0.8
{
  "nodes": [
    ["node1", "https://123.com/x.php"],
    ["node2", "https://456.com/x.php"]
  ]
}
比如这样配置会导致node2无法正常加载，请问是bug还是就是设定节点名称不能相同？

**Comment by kmvan** [comment]
名称不能相同
