### ISSUE TITLE
虚拟主机使用会存在问题，希望得到改进

### ISSUE THREAD

**Issue by Adsryen** [kmvan/x-prober#175]
- OS: 
- PHP version: 7.4
- Browser: edge

## Other description
<!-- Your contents --

报错如下：
![截图20211028022629](https://user-images.githubusercontent.com/51238895/139125129-27594932-5404-458a-9dc2-a552fc3d7855.png)
>

**Comment by kmvan** [comment]
该问题因长时间无回复被关闭。如问题为解决可重新打开继续讨论或继续展开讨论。
