### ISSUE TITLE
不兼容较旧的PHP版本

### ISSUE THREAD

**Issue by AdminHcat** [kmvan/x-prober#177]
- OS: Linux 2.6.31.8
- PHP version: 5.4
- Browser: Chrome 98.0.4

似乎没有向下版本兼容性
望兼容旧版本PHP
![image](https://user-images.githubusercontent.com/50044729/144738192-a22807d9-a7cc-4555-8537-8c322f8b5b25.png)

**Comment by kmvan** [comment]
更新到 8.7 版本试试，应该可以了。

**Comment by AdminHcat** [comment]
> 更新到 8.7 版本试试，应该可以了。

nice ！阔以了
