### ISSUE TITLE
How to close the test of 60 seconds?

### ISSUE THREAD

**Issue by byebvip** [kmvan/x-prober#195]
- OS:
- PHP version: 

Want to close the running score test 60 seconds limit

It must wait for 60s?

**Comment by kmvan** [comment]
This is to prevent malicious operations.
You can delete `/tmp/xproberBenchmarkTimer` file to reset timer.

**Comment by kmvan** [comment]
Not now. Maybe release this feature on next version.

**Comment by byebvip** [comment]
> Not now. Maybe release this feature on next version.

Okay, because I read the code and feel too complicated, I can't restart it

**Comment by kmvan** [comment]
Have a try version 8.16 and add `"serverBenchmarkCd": 30,` into `xconfig.json` config file.
