### ISSUE TITLE
更多硬盘状态显示

### ISSUE THREAD

**Issue by 0xffffharry** [kmvan/x-prober#210]
**Is your feature request related to a problem? Please describe.**

目前系统中挂载多块硬盘，并且想显示各硬盘的使用温度，希望可以支持，感谢

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kmvan** [comment]
显示多块硬盘可以，目前是显示探针所在的硬盘分区。
显示硬盘温度这个需要研究研究

**Comment by 0xffffharry** [comment]
php存在诸多限制，有考虑使用其他语言重写并发布二进制可执行文件吗

**Comment by kmvan** [comment]
正有此计划

Nov 23, 2023 19:32 wrote on 0xffffharry ***@***.***>:

php存在诸多限制，有考虑使用其他语言重写并发布二进制可执行文件吗

**Comment by kmvan** [comment]
今天抽空我尝试了一下，使用 `/proc/mounts` 来获取所有磁盘分区，然后通过 `disk_total_space` 和 `disk_free_space` 来显示各个分区的可用容量信息。但发现除了 root 用户权限能获取全部磁盘信息外，默认 www-data 用户只能获取本文件所在的磁盘信。所以似乎获取全部磁盘信息难以实现，`/proc` 目录内也没有其他关于磁盘使用量的模块了。这个功能还真有点难度，我会找找其他方法实现。

**Comment by kmvan** [comment]
想了下，打算用Go来重构，能在shell中显示和网页显示，也能获取更多信息。

**Comment by kmvan** [comment]
如果你的PHP环境可以执行 shell_exec 函数，那下个版本可以显示其他硬盘空间。

**Comment by kmvan** [comment]
已更新到8.17版本，使用了 shell_exec 系统函数来增加显示磁盘空间。
如果问题欢迎继续讨论。
