### ISSUE TITLE
请问在纯 IPv6 VPS 下，不能更新吗？

### ISSUE THREAD

**Issue by xanadus1** [kmvan/x-prober#29]
- OS: Ubuntu 18.04.2
- PHP version: 7.2.6
***
点击更新，提示：无法更新文件。
尝试修改权限为 777 后，点击更新，提示：未找到更新文件。

还是因为更新需要访问 Github？（Github 不支持 IPv6。）
这个 https://api.inn-studio.com/download?id=xprober 支持 IPv6。

或是我的设置问题？网络问题？

谢谢。

**Comment by kmvan** [comment]
从 2.3.0 版本开始有多点更新源了。
