### ISSUE TITLE
[BUG] 服务器跑分显示为负数

### ISSUE THREAD

**Issue by urusai-me** [kmvan/x-prober#44]
- OS: Windows 10 1903
- PHP version: 7.3.9
- WebServer: IIS10

** Report content **
跑分不正常，输出如下：

> `我的服务器 848HASH+ 908INT+ 884FLOAT+ -15,865IO= -13,225`

同样问题出现在作者的[演示站点](https://prober.inn-studio.com/)，输出如下：

> `我的服务器 409HASH+ -443INT+ -596FLOAT+ -365IO= -995`

**Comment by kmvan** [comment]
负数是因为性能太弱导致的。并不是bug。
跑分时候判定的是当前主机的性能状态，主机有可能正处于繁忙期，所以导致性能低下，继而分数降低。
分数没有下限的。

**Comment by urusai-me** [comment]
> 负数是因为性能太弱导致的。并不是bug。
> 跑分时候判定的是当前主机的性能状态，主机有可能正处于繁忙期，所以导致性能低下，继而分数降低。
> 分数没有下限的。

但是我这边主机性能应该没问题才对，i5 7600K + EVO 970 PRO +32G ddr4物理机运行，除了web服务以外什么都没跑，看资源管理器也全都空闲……

**Comment by kmvan** [comment]
> 我的服务器 848HASH+ 908INT+ 884FLOAT+ -15,865IO= -13,225

cpu 性能都不错，但磁盘 io（小文件读写）性能比较弱。
你的是windows，可以试试关掉 windows defender 这个性能大杀器，或者关掉杀软，因为它们都会在测试写入时候降低效率的。
如果是服务器，那么有可能运营商添加的“杀软/监控（例如阿里的监控骑士）”也对io有所影响。

**Comment by urusai-me** [comment]
> 我的服务器 848HASH+ 908INT+ 884FLOAT+ -15,865IO= -13,225
> 
> cpu 性能都不错，但磁盘 io（小文件读写）性能比较弱。
> 你的是windows，可以试试关掉 windows defender 这个性能大杀器，或者关掉杀软，因为它们都会在测试写入时候降低效率的。
> 如果是服务器，那么有可能运营商添加的“杀软/监控（例如阿里的监控骑士）”也对io有所影响。

好的我试试，谢谢！

**Comment by Cathgao** [comment]
> > 我的服务器 848HASH+ 908INT+ 884FLOAT+ -15,865IO= -13,225
> 
> cpu 性能都不错，但磁盘 io（小文件读写）性能比较弱。
> 你的是windows，可以试试关掉 windows defender 这个性能大杀器，或者关掉杀软，因为它们都会在测试写入时候降低效率的。
> 如果是服务器，那么有可能运营商添加的“杀软/监控（例如阿里的监控骑士）”也对io有所影响。

我的是j1900+杂牌16GB msata固态，也出现了跑分负数，IO分数-200~-350。
系统环境为Ubuntu19.10 | nginx1.16.1 | PHP7.3.11
虽然说这个硬盘性能真的是差，但我感觉这个分数还是有点太怪了，我性能绝对要比970EVO差上千倍，但负分还没他高。
![hw](https://user-images.githubusercontent.com/21031564/76927372-b92c2b80-6919-11ea-8af0-58157007264c.png)
![sc](https://user-images.githubusercontent.com/21031564/76927255-7407f980-6919-11ea-935b-3f449b8908f2.png)

**Comment by kmvan** [comment]
分数为负的，说明了没在指定时间内完成测试，所以分数无下限。一般不是服务器硬盘都很容易跑出负分。
