### ISSUE TITLE
raw.githubusercontent.com 被污染

### ISSUE THREAD

**Issue by fx0817** [kmvan/x-prober#47]
- OS:
- PHP version: 

*** Your content ***
国内ip无法访问 raw.githubusercontent.com 也就无法在线更新

**Comment by kmvan** [comment]
那咋整？
如果使用自建更新源，就怕被别有用心的人说加了料。

**Comment by fx0817** [comment]
> 那咋整？
> 如果使用自建更新源，就怕被别有用心的人说加了料。

当然是 http://github.io  手动续命，不用自己流量。(斜眼笑
当整个github都被污染了，再说呗。

**Comment by kmvan** [comment]
也行，加上多源更新，问题应该不大。

**Comment by jonsonjordan** [comment]
大不了手动更新

**Comment by kmvan** [comment]
下个版本我再加一个自建源更新。同时开源更新源代码就行

**Comment by kmvan** [comment]
已确认下个版本（3.7）将会有两个更新源：
- Github
- INN
