### ISSUE TITLE
真心希望能加入中文

### ISSUE THREAD

**Issue by 8838** [kmvan/x-prober#74]
- OS:
- PHP version: 

*** Your content ***

**Comment by kmvan** [comment]
多国语言的，会自动根据浏览器语言来显示。

**Comment by 8838** [comment]
手机Safari浏览器打开是英文，那这是怎么回事呀

**Comment by kmvan** [comment]
探针拉到最底，复制 UA 和语言信息贴来看看？

**Comment by 8838** [comment]
http://ios.lu/x.php

**Comment by 8838** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1

下面2行显示的zh-cn

**Comment by kmvan** [comment]
是 zh-CN 还是 zh-cn？

**Comment by 8838** [comment]
2行都是小写zh-cn

**Comment by kmvan** [comment]
看样子是探针没有忽略大小写语言导致的，下个版本会忽略大小写，应该能正常显示

**Comment by 8838** [comment]
那就是一个很小的问题啦，希望能尽快修复。强迫症😅。感谢

**Comment by kmvan** [comment]
> 那就是一个很小的问题啦，希望能尽快修复。强迫症。感谢

试试下载开发版：https://github.com/kmvan/x-prober/tree/dev/dist 文件另存为，保存到服务器测试看看

**Comment by 8838** [comment]
你发这个我不会安装……

**Comment by 8838** [comment]
> > 那就是一个很小的问题啦，希望能尽快修复。强迫症。感谢
> 
> 试试下载开发版：https://github.com/kmvan/x-prober/tree/dev/dist 文件另存为，保存到服务器测试看看

4.5版本已经正常显示了中文
