### ISSUE TITLE
Statistics in Network Stats will not update after exceeding 2G

### ISSUE THREAD

**Issue by busymx** [kmvan/x-prober#79]
- OS: Raspbian (Kernel Version: 4.19)
- PHP version: 7.0.33

*** Your content ***

![123](https://user-images.githubusercontent.com/24978668/79694909-25e26f00-82a6-11ea-97a3-b03b85be0975.png)

When the network traffic exceeds 2G, neither real-time traffic statistics nor total traffic statistics will update.
当网络流量超过2G之后，无论是实时流量统计，还是总流量统计都不会再更新。

Note: I have only seen this situation on the Raspberry Pi 3B(armv7). The Nginx version is 1.16.0.
注：我只在树莓派3B上看到过这种情况，Nginx版本是1.16。

英语水平有限，我尽量去写，中英文表达不一致的地方以中文为准，打扰了。

**Comment by kmvan** [comment]
当超过2G后，服务器信息的时间，是否会持续更新？

**Comment by busymx** [comment]
![image](https://user-images.githubusercontent.com/24978668/79786091-7f669e80-8377-11ea-9a76-069a68ef89af.png)
时间信息保持更新。

**Comment by kmvan** [comment]
当超过2G后，探针没有变化时，试试终端输入：

```shell
watch -n 1 'cat /proc/net/dev'
```

在进行网络传输的同时观察数字是否有变化？探针是根据这个文件输出显示的。

**Comment by busymx** [comment]
终端命令及时变化，但是X Prober 页面没有更新。
录了一个小视频片段：https://youtu.be/xSLFXlH2cQQ

**Comment by kmvan** [comment]
这个就很奇怪了，有在线地址吗？可能我需要检查一下请求。

**Comment by busymx** [comment]
http://cn.xiaox.me:20079/xprober.php
非常感谢。

**Comment by busymx** [comment]
![image](https://user-images.githubusercontent.com/24978668/79952929-ba6aee00-84ad-11ea-9e76-b24f002506e5.png)

2147483647，整数边界？我其他的机器都是x86_64，没这个问题。

**Comment by kmvan** [comment]
看样子，确实是 32 位系统的最大 int 值（正负2G/正4G）
看来得把 int 改成 float 才可以。开发版我尝试一下，到时候弄好跟你说下，然后你下载开发版测试测试。

**Comment by kmvan** [comment]
@busymx 试试下载开发版测试一下：https://github.com/kmvan/x-prober/tree/dev/dist

**Comment by busymx** [comment]
开发版没问题了，感谢！
