### ISSUE TITLE
[Feature request] 功能去除

### ISSUE THREAD

**Issue by SeireiA** [kmvan/x-prober#85]
您好，本人觉得服务器跑分和PHP禁用函数等一些可以对服务器造成危害的功能可以去除，或者有个开关也可以哇
别人可以通过服务器跑分消耗服务器性能，可以通过禁用的函数省去一些步骤
纯属建议(狗头保命

**Comment by kmvan** [comment]
这个建议不错，有考虑使用配置文件来开关功能

**Comment by SeireiA** [comment]
问一下哈，这个跑分正常情况能核心全开嘛，8核感觉跑分测试的时候只有一两个在跑

**Comment by kmvan** [comment]
探针的跑分，是基于服务器执行 PHP 运算效率得出的结果。
目前探针没有使用多线程运算，而是针对单核来进行性能测试，这样做的原因是因为目前大多数 PHP 程序都只有单线程逻辑，所以这样测试比较能体现服务器的综合性能。
故无论是10核或100核，同样的配置，分数并不会有太多变化，但核心越多，服务器能抗的并发也就越多，这个是分数所不能体现的，要根据服务器的实际应用来考虑，分数只是一个基本的测量。

**Comment by kmvan** [comment]
当然未来不排除使用协程之类的，但那是后话了

**Comment by SeireiA** [comment]
好的，感谢

**Comment by SeireiA** [comment]
对了，还有个小请求，就是README.md
里面加一条更新日志可以咩，就是几月几号更新的更新的啥（

**Comment by kmvan** [comment]
changelog.md 里面有

**Comment by SeireiA** [comment]
抱歉，没注意看过
就等配置文件开关功能啦🌚

**Comment by kmvan** [comment]
![image](https://user-images.githubusercontent.com/3839554/89794138-39695c80-db59-11ea-93f8-39cefec182e5.png)

估计下个版本就有配置文件

**Comment by kmvan** [comment]
Added in 4.10

https://github.com/kmvan/x-prober/wiki/xconfig.json-settings
