### ISSUE TITLE
[BUG] stop at loading...

### ISSUE THREAD

**Issue by feelkiller** [kmvan/x-prober#86]
- OS:centos
- PHP version:7.3

** Report content **
the page stop at 'Loading...' from version 4.2 to 4.8
there should be something wrong due to Reduce JS file size

**Comment by kmvan** [comment]
Any online page address?

**Comment by feelkiller** [comment]
> Any online page address?

your demo is same to mine.
https://prober.inn-studio.com/

**Comment by kmvan** [comment]
What's your browser?

**Comment by feelkiller** [comment]
> What's your browser?

I tried Edge / IE / Chrome. All of them was not working.
version 4.1 and before is ok.

**Comment by kmvan** [comment]
Show the browser's `About` infomation and paste here.
Likes: 
![image](https://user-images.githubusercontent.com/3839554/82111965-6df89280-977b-11ea-993d-69e24e593336.png)

**Comment by feelkiller** [comment]
Chromium | 57.0.2987.98
the version is too old
but edge and ie are not working either.

**Comment by kmvan** [comment]
What's the edge version?

**Comment by tyrsrd** [comment]
its not work in directadmin server panel. what requirement extention?
thank's

**Comment by kmvan** [comment]
If there is no more information, I will close the issue. But this does not mean that this issue cannot be discussed, please feel free to discuss and open it.
