### ISSUE TITLE
stuck in loading

### ISSUE THREAD

**Issue by tjc0726** [kmvan/x-prober#89]
- OS: Centos
- PHP version:7.4.6 
- Client Browser: Edge

The console in edge shows that
![image](https://user-images.githubusercontent.com/49085201/83968152-b9750b00-a8f9-11ea-97ba-db109690b51c.png)
![image](https://user-images.githubusercontent.com/49085201/83968195-fc36e300-a8f9-11ea-8521-d8c4507c5d46.png)

BTW it works fine on my chrome in the same device

**Comment by kmvan** [comment]
What's your EDGE version?

**Comment by kmvan** [comment]
Update to lastest Edge version (not EdgeHTML)

**Comment by tjc0726** [comment]
> Update to lastest Edge version (not EdgeHTML)

As far as I know, the update of Edge can only occur in the windows setting: update and security,
however, there's no update available in my device(as they're the latest), and because the Windows 2004 is GrayReleased, I haven't received the update of the Edge which should be bound with Windows 2004.

![image](https://user-images.githubusercontent.com/49085201/83970704-af5b0880-a909-11ea-8bac-bf8490379c5c.png)

**Comment by kmvan** [comment]
You will get the new Edge soon or dowload the new version from Microsoft https://www.microsoft.com/en-us/edge.
I think the old Edge is dead and no one wants to commemorate it.

**Comment by tjc0726** [comment]
> You will get the new Edge soon or dowload the new version from Microsoft https://www.microsoft.com/en-us/edge.
> I think the old Edge is dead and no one wants to commemorate it.

Agreed, thanks for the reply
