### ISSUE TITLE
Not show information in Server Status

### ISSUE THREAD

**Issue by bakhtiyarsierad** [kmvan/x-prober#90]
- OS: Centos 7.7.1908
- PHP version:  7.3.19

its not work in directadmin server panel. what requirement extention?
thank's

![Image 3](https://user-images.githubusercontent.com/7570307/86593719-ec292680-bfbf-11ea-93b0-674b85e9ec94.png)

**Comment by kmvan** [comment]
Can the PHP access `/proc` dir? Because the network stats info comes from `/proc/net/dev`.
You can add a line:
```
fastcgi_param  PHP_VALUE          "open_basedir=$document_root:/tmp/:/proc    /";
```
to your nginx's `fastcgi.conf` file if you are using nginx.

**Comment by kmvan** [comment]
Almost all system info comes from `/proc`.

**Comment by tyrsrd** [comment]
when i use php-fpm? where to do that?

**Comment by kmvan** [comment]
You are using Apache right?

**Comment by tyrsrd** [comment]
yes i using apacbe

**Comment by kmvan** [comment]
Sorry, I don't how to let Apache access `/proc` dir. I am not sure how to fix it.
Maybe https://askubuntu.com/questions/325498/apache-cant-access-folders-in-my-home-directory ? Not sure. 
BTW, why not try to use Nginx? Apache is out data, Nginx in a right way.

**Comment by kmvan** [comment]
If there is no more information, I will close the issue. But this does not mean that this issue cannot be discussed, please feel free to discuss and open it.

**Comment by horasjey** [comment]
i have this problem sir,
how to solved it..?
in my vps
![image](https://github.com/kmvan/x-prober/assets/45363813/fca5d392-0ccb-4cb2-a1dc-e97e535f1832)

**Comment by horasjey** [comment]
![image](https://github.com/kmvan/x-prober/assets/45363813/14f3804a-8385-4411-abb7-b15ef43ba5cc)

**Comment by kmvan** [comment]
Hi man.
This looks like PHP-fpm doesn't have permission to read the /proc directory.
You can add
*fastcgi_param  PHP_VALUE
 "open_basedir=$document_root:/tmp/:/proc/";*
to
*/etc/nginx/fastcgi.conf*
and reload nginx.
Have a try.

**Comment by horasjey** [comment]
> i man. This looks like PHP-fpm doesn't have permission to read the /proc directory. You can add *fastcgi_param PHP_VALUE "open_basedir=$document_root:/tmp/:/proc/";* to */etc/nginx
like my problem in this section File(/proc/net/dev)
![image](https://github.com/kmvan/x-prober/assets/45363813/e295f3a0-ce99-4bab-bcc5-066b190ee051)

`    $output = shell_exec('cat /proc/net/dev');
$netDevData = explode("\n", $output);
$netDevData = array_filter($fileContent, 'strlen');`
![image](https://github.com/kmvan/x-prober/assets/45363813/142c0b08-c88e-41ab-b3ee-6bd06d842c44)

Now,
How do you implement it into x-prober?

**Comment by kmvan** [comment]
You need to give php-fpm permission to read the /proc directory.

**Comment by horasjey** [comment]
i dont have permision , but my vps not user root,

and now my isue solved modif your file php

![image](https://github.com/kmvan/x-prober/assets/45363813/187221da-0aff-4f20-a99d-96ccf3cb0975)

**Comment by kmvan** [comment]
Okay.
